name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - UAT
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Verify Flutter
        run: flutter --version

      - name: Get Dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href /email/

      - name: Upload Build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.TOMCAT_HOST }}
          username: ${{ secrets.TOMCAT_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/web/*"
          target: "/tmp/flutter-build"

      - name: Deploy to Tomcat
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.TOMCAT_HOST }}
          username: ${{ secrets.TOMCAT_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /opt/tomcat9/webapps/email
            sudo rm -rf /opt/tomcat9/webapps/email/*
            sudo cp -r /tmp/flutter-build/build/web/* /opt/tomcat9/webapps/email/
            echo "Flutter deployment completed"
